version: '1'
services:
    tutor_app:
        container_name: tutor_app
        volumes:
            - ./:/app
        build: .
        stdin_open: true
        tty: true
        ports:
            - '8000:8000'