# Generated by Django 4.1.2 on 2022-11-11 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_groups_grouplesson_groupinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttask',
            name='text_answer',
            field=models.TextField(blank=True, default=None, verbose_name='Answer'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='members.teacher')),
            ],
        ),
    ]
