# Generated by Django 4.1.2 on 2022-11-12 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='lesson_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GroupLessonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_data', models.DateField()),
                ('group_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_paid', to='members.grouplesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_payments', to='members.student')),
            ],
        ),
    ]
